FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# zenjob-tvs-mock-verification

Verification API (REST) that will be consumed by the GraphQL Gateway.

## Document Count [/documents/count]

### GET THE NUMBER OF DOCUMENTS [GET]

+ Request (application/json)

    + Headers

            Authorization: "Berarer ..."


+ Response 200 (application/json)


        {
            "count": 114
        }


## Document Assignment [/documents/assign]

### ASSIGN NEXT DOCUMENT [PUT]

+ Request (application/json)

    + Headers

            Authorization: "Berarer ..."


+ Response 200 (application/json)


        {
            "id": "098F6BCD4621D373CADE4E832627B4F6",
            "location": "http://www.orimi.com/pdf-test.pdf",
            "type": "Imma",
            "uploadedBy": "John Doe",
            "uploadDate": "2018-03-19T12:00:00Z",
            "metadata": [{
                { name: "Matriculation Date", value: "01.10.2013" },
                { name: "Current Term", value: "Summer 2015" },
                { name: "Semester Period", value: "15.03.2015 - 30.09.2015"}
            }]
        }


## Document Unassignment [/documents/{id}/unassign]

### UNASSIGN DOCUMENT [PUT]


+ Request (application/json)

    + Headers

            Authorization: "Berarer ..."


+ Response 201 (application/json)


    + Body

        {
            "id": "098F6BCD4621D373CADE4E832627B4F6",
            "location": "http://www.orimi.com/pdf-test.pdf",
            "type": "Imma",
            "uploadedBy": "John Doe",
            "uploadDate": "2018-03-19T12:00:00Z",
            "metadata": [{
                { name: "Matriculation Date", value: "01.10.2013" },
                { name: "Current Term", value: "Summer 2015" },
                { name: "Semester Period", value: "15.03.2015 - 30.09.2015"}
            }]
        }


## Document Verify [/documents/{id}/verify]

### VERIFY THE DOCUMENT [PUT]

+ Request (application/json)

    + Headers

            Authorization: "Berarer ..."
            
    + Body

        {
        }


+ Response 200 (application/json)


        {
            "id": "098F6BCD4621D373CADE4E832627B4F6",
            "location": "http://www.orimi.com/pdf-test.pdf",
            "type": "Imma",
            "uploadedBy": "John Doe",
            "uploadDate": "2018-03-19T12:00:00Z",
            "metadata": [{
                { name: "Matriculation Date", value: "01.10.2013" },
                { name: "Current Term", value: "Summer 2015" },
                { name: "Semester Period", value: "15.03.2015 - 30.09.2015"}
            }]
        }
        
        
        
## Document Reject [/documents/{id}/reject]

### REJECT THE DOCUMENT [PUT]

+ Request (application/json)

    + Headers

            Authorization: "Berarer ..."
            
    + Body

        {
            reasonCode: "OTHER",
            reasonText: "Not valid ..."
        }


+ Response 200 (application/json)


        {
            "id": "098F6BCD4621D373CADE4E832627B4F6",
            "location": "http://www.orimi.com/pdf-test.pdf",
            "type": "Imma",
            "uploadedBy": "John Doe",
            "uploadDate": "2018-03-19T12:00:00Z",
            "metadata": [{
                { name: "Matriculation Date", value: "01.10.2013" },
                { name: "Current Term", value: "Summer 2015" },
                { name: "Semester Period", value: "15.03.2015 - 30.09.2015"}
            }]
        }
        
        
## Get Reject Reasons [/rejectReasons]

### GET REJECT REASONS [GET]

+ Request (application/json)

    + Headers

            Authorization: "Berarer ..."
            


+ Response 200 (application/json)


        [
            { code: "DOCUMENT_UNREADABLE" },
            { code: "WRONG_DATA" },
            { code: "WRONG_DOCUMENT" },
            { code: "OTHER" }
        ]